name: Evercode checks

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Select Xcode
        run: sudo xcode-select -switch /Applications/Xcode_14.1.app && /usr/bin/xcodebuild -version

      - name: Download mock file
        run: curl -0 https://devpass-api-bucket.s3.amazonaws.com/testes/FreddyVsJsonSwiftTests/Mock.json -o GitHubAppTests/Mock.json

      - name: Download NetworkMock file
        run: curl -0 https://devpass-api-bucket.s3.amazonaws.com/testes/FreddyVsJsonSwiftTests/NetworkMock.swift -o GitHubAppTests/NetworkMock.swift

      - name: Download test file
        run: curl -0 https://devpass-api-bucket.s3.amazonaws.com/testes/FreddyVsJsonSwiftTests/ServiceTests.swift -o GitHubAppTests/ServiceTests.swift

      - name: Run Unit Tests
        run: xcodebuild test -scheme GitHubApp -project GitHubApp.xcodeproj -destination 'platform=iOS Simulator,name=iPhone 14 Pro,OS=16.1' | xcpretty && exit ${PIPESTATUS[0]}